export const API_URL = "http://65.20.82.161/pl_api2/api/";

//demo
// export const API_URL = "http://65.20.82.161/pcapi_demo/api/";

export const SideMenuWidth = 240;

export const DrawerWidth = 650;

export const FOOTER_COLORS: any = {
  success: "#357a38",
  warn: "#ffa000",
  error: "#d32f2f",
  default: "#313131",
};

export const PRIMARY_COLOR = "#2196f3";
export const SECONDARY_COLOR = "#009688";
export const COLOR_WHITE = "#fff";
export const COLOR_BLACK = "#0000";

export const HEADER_COLOR = "#1b68c0";

export const TABLE_NAMES = {
  AUDIT_LOCATIONS: "AUDIT_LOCATIONS",
  BMR_CANCELLATION_REASONS: "BMR_CANCELLATION_REASONS",
  BMR_CANCELLATION_REQUEST: "BMR_CANCELLATION_REQUEST",
  BOM: "BOM",
  BOM_DETAILS: "BOM_DETAILS",
  BOM_STATUS: "BOM_STATUS",
  CALENDAR_DATA: "CALENDAR_DATA",
  CAPA: "CAPA",
  CAPA_AREA: "CAPA_AREA",
  CAPA_CATEGORY: "CAPA_CATEGORY",
  CAPA_REFERENCE_TYPE: "CAPA_REFERENCE_TYPE",
  CAPA_STATUS: "CAPA_STATUS",
  CAPACITY: "CAPACITY",
  CERTIFICATE_OF_ANALYSIS: "CERTIFICATE_OF_ANALYSIS",
  CHANGE_REQUEST: "CHANGE_REQUEST",
  CHECKLIST_TYPES: "CHECKLIST_TYPES",
  COA_REMARKS: "COA_REMARKS",
  COA_STATUS: "COA_STATUS",
  COLOR: "COLOR",
  COMPLAINT_INVESTIGATION_REPORT: "COMPLAINT_INVESTIGATION_REPORT",
  COMPLIANCE_STATUS: "COMPLIANCE_STATUS",
  DATACOLLECTION_ITEMS: "DATACOLLECTION_ITEMS",
  DATACOLLECTION_VALUES: "DATACOLLECTION_VALUES",
  DESTRUCTION_NOTE_STATUS: "DESTRUCTION_NOTE_STATUS",
  DEVIATION: "DEVIATION",
  EMAIL_CONFIG_DETAILS: "EMAIL_CONFIG_DETAILS",
  EMPLOYEE: "EMPLOYEE",
  EQUIPMENT_HISTORIAN_DATA: "EQUIPMENT_HISTORIAN_DATA",
  ESIG_DEFINITIONS: "ESIG_DEFINITIONS",
  ESIG_REQUIREMENT_TYPES: "ESIG_REQUIREMENT_TYPES",
  ESIG_VALUES: "ESIG_VALUES",
  FG_ISSUE_DETAILS: "FG_ISSUE_DETAILS",
  FG_ISSUE_HEADER: "FG_ISSUE_HEADER",
  FG_ISSUE_STATUS: "FG_ISSUE_STATUS",
  FGTN_DETAILS: "FGTN_DETAILS",
  FGTN_HEADER: "FGTN_HEADER",
  FGTN_ISSUE_DETAILS: "FGTN_ISSUE_DETAILS",
  FGTN_ISSUE_HEADER: "FGTN_ISSUE_HEADER",
  FGTN_ISSUE_HISTORY: "FGTN_ISSUE_HISTORY",
  FGTN_ISSUE_STATUS: "FGTN_ISSUE_STATUS",
  FGTN_STATUS: "FGTN_STATUS",
  FM_ORDER_HEADER: "FM_ORDER_HEADER",
  GOODS_RECEIPT_NOTE: "GOODS_RECEIPT_NOTE",
  INCIDENT_CATEGORY: "INCIDENT_CATEGORY",
  INCIDENT_NATURE: "INCIDENT_NATURE",
  INCIDENT_REPORTING: "INCIDENT_REPORTING",
  INCIDENT_STATUS: "INCIDENT_STATUS",
  INSPECTION_AUDIT_PLAN: "INSPECTION_AUDIT_PLAN",
  INSPECTION_AUDIT_STATUS: "INSPECTION_AUDIT_STATUS",
  INSPECTION_INTIMATION_SLIP: "INSPECTION_INTIMATION_SLIP",
  INSPECTION_REPORT: "INSPECTION_REPORT",
  INSPECTION_RESPONSE: "INSPECTION_RESPONSE",
  INSPECTION_RESPONSE_STATUS: "INSPECTION_RESPONSE_STATUS",
  INSPECTION_SLIP_STATUS: "INSPECTION_SLIP_STATUS",
  LABEL_PRINT_HISTORY: "LABEL_PRINT_HISTORY",
  LOG_BOOK_DETAILS: "LOG_BOOK_DETAILS",
  LOG_BOOK_HISTORY: "LOG_BOOK_HISTORY",
  LOG_BOOKS: "LOG_BOOKS",
  LOGIN_DETAILS: "LOGIN_DETAILS",
  MATERIAL_CHECKLIST: "MATERIAL_CHECKLIST",
  MATERIAL_DESTRUCTION_NOTE: "MATERIAL_DESTRUCTION_NOTE",
  MATERIAL_DETAILS: "MATERIAL_DETAILS",
  MATERIAL_DISPATCH_DETAILS: "MATERIAL_DISPATCH_DETAILS",
  MATERIAL_HANDLING_HISTORY: "MATERIAL_HANDLING_HISTORY",
  MATERIAL_MASTER: "MATERIAL_MASTER",
  MATERIAL_STATUS: "MATERIAL_STATUS",
  MATERIAL_TYPE: "MATERIAL_TYPE",
  MATERIAL_UOM_CONVERSION: "MATERIAL_UOM_CONVERSION",
  MENU_ASSIGNMENT: "MENU_ASSIGNMENT",
  MENU_GROUPS: "MENU_GROUPS",
  MENU_ITEMS: "MENU_ITEMS",
  MFG_LINE: "MFG_LINE",
  MFG_PLANT: "MFG_PLANT",
  MFG_SITE: "MFG_SITE",
  MFG_STAGE: "MFG_STAGE",
  NCR_AREA: "NCR_AREA",
  NCR_DETAILS: "NCR_DETAILS",
  NCR_HEADER: "NCR_HEADER",
  NCR_ITEMS: "NCR_ITEMS",
  NCR_STATUS: "NCR_STATUS",
  NOCONFORMANCE_REPORT: "NOCONFORMANCE_REPORT",
  OBJECT_STATUS: "OBJECT_STATUS",
  OBSERVATION_TYPES: "OBSERVATION_TYPES",
  ORDER_DETAILS: "ORDER_DETAILS",
  ORDER_DETAILS_HISTORY: "ORDER_DETAILS_HISTORY",
  ORDER_HEADER: "ORDER_HEADER",
  ORDER_STATUS: "ORDER_STATUS",
  PACKING_TYPES: "PACKING_TYPES",
  PHARMACOPIA: "PHARMACOPIA",
  PM_ANNUAL_PLAN: "PM_ANNUAL_PLAN",
  PM_ORDER_HEADER: "PM_ORDER_HEADER",
  PROCESS_INSTRUCTIONS: "PROCESS_INSTRUCTIONS",
  PROCESS_INSTRUCTIONS_DETAILS: "PROCESS_INSTRUCTIONS_DETAILS",
  PRODUCT_COMPLAINTS: "PRODUCT_COMPLAINTS",
  PRODUCT_STATUS: "PRODUCT_STATUS",
  RECIPE: "RECIPE",
  RECIPE_STAGES: "RECIPE_STAGES",
  RECIPE_STATUS: "RECIPE_STATUS",
  RECIPE_TASKS: "RECIPE_TASKS",
  RESOURCE: "RESOURCE",
  RESOURCE_ALLOCATIONS: "RESOURCE_ALLOCATIONS",
  RESOURCE_CHECKLIST: "RESOURCE_CHECKLIST",
  RESOURCE_STATUS: "RESOURCE_STATUS",
  RESOURCE_STATUS_HISTORY: "RESOURCE_STATUS_HISTORY",
  RESPONSE_NOTES: "RESPONSE_NOTES",
  SAMPLE_ANALYSIS_REQUEST: "SAMPLE_ANALYSIS_REQUEST",
  SAMPLE_ANALYSIS_STATUS: "SAMPLE_ANALYSIS_STATUS",
  SAMPLING_PLAN_FG: "SAMPLING_PLAN_FG",
  SAMPLING_PLAN_NOTES: "SAMPLING_PLAN_NOTES",
  SAMPLING_PLAN_PKNG_CONTAINERS: "SAMPLING_PLAN_PKNG_CONTAINERS",
  SAMPLING_PLAN_PKNG_FOILS: "SAMPLING_PLAN_PKNG_FOILS",
  SERVICE_REQUEST_DETAILS: "SERVICE_REQUEST_DETAILS",
  SERVICE_REQUEST_HEADER: "SERVICE_REQUEST_HEADER",
  SERVICE_REQUEST_STATUS: "SERVICE_REQUEST_STATUS",
  SFG_ISSUE_DETAILS: "SFG_ISSUE_DETAILS",
  SFG_ISSUE_STATUS: "SFG_ISSUE_STATUS",
  SHAPE: "SHAPE",
  SHIPMENT_CONTAINER_DETAILS: "SHIPMENT_CONTAINER_DETAILS",
  SHIPMENT_DETAILS: "SHIPMENT_DETAILS",
  SHIPMENT_METHODS: "SHIPMENT_METHODS",
  SITE_CONFIG_DETAILS: "SITE_CONFIG_DETAILS",
  SPECIFICATION_DETAILS: "SPECIFICATION_DETAILS",
  SPECIFICATION_HEADER: "SPECIFICATION_HEADER",
  SPECIFICATION_STATUS: "SPECIFICATION_STATUS",
  SPECIFICATION_TYPES: "SPECIFICATION_TYPES",
  STORAGE_LOCATIONS: "STORAGE_LOCATIONS",
  TASK_DC_ITEMS: "TASK_DC_ITEMS",
  TASK_TYPES: "TASK_TYPES",
  TEST_METHOD_HEADER: "TEST_METHOD_HEADER",
  TEST_METHOD_ITEMS: "TEST_METHOD_ITEMS",
  TEST_METHOD_TYPE: "TEST_METHOD_TYPE",
  UOM: "UOM",
  USER_ALLOCATIONS: "USER_ALLOCATIONS",
  USER_GROUPS: "USER_GROUPS",
  USER_ROLES: "USER_ROLES",
  VENDOR_DETAILS: "VENDOR_DETAILS",
  VENDOR_STATUS: "VENDOR_STATUS",
  WAREHOUSE_LOCATION: "WAREHOUSE_LOCATION",
  WORKORDER_CATEGORY: "WORKORDER_CATEGORY",
  WORKORDER_TYPES: "WORKORDER_TYPES"
}

export const API_METHOD_TYPES = {
  POST: "POST",
  GET: "GET",
  DELETE: "DELETE"
}

export const API_QUERY = {
  getTableFieldCaptions: "getTableFieldCaptions",
  getTransactionObject: "getTransactionObject"
}

export const USER_GROUPS = {
  QualityAssurance: "Quality Assurance",
  Warehouse: "Warehouse"
}

export const USER_ROLES = {
  HOD: "HOD"
}

export const LIST_SV={
  getDestructionNoteStatusSV:"getDestructionNoteStatusSV",
  getWorkOrderTypesListSV:"getWorkOrderTypesListSV"
}